export type ExportTab = 'coffee' | 'sesame';

export type ExportRow = {
  id: number;
  week: string;
  shipmentNo: string;
  buyer: string;
  destination: string;
  quantity: number;
  unit: string;
  containers: number;
  pricePerKg: number;
  grossUsd: number;
  paidUsd: number;
  paymentStatus: 'Paid' | 'Partial' | 'Open';
  cleaning: string;
  product: string;
  vessel: string;
  contract: string;
  status: 'Delivered' | 'In Transit' | 'At Port' | 'On Vessel' | 'Pending';
  date: string;
  notes: string;
};

export const coffeeSeed: ExportRow[] = [
  {
    "id": 1,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/402/08/2025",
    "buyer": "REMEDAN",
    "destination": "EGYPT",
    "quantity": 38,
    "unit": "MT",
    "containers": 2,
    "pricePerKg": 2.6,
    "grossUsd": 217814.48,
    "paidUsd": 21781.45,
    "paymentStatus": "Partial",
    "cleaning": "completed",
    "product": "WASHED LIMMU GR-UG",
    "vessel": "NOT RECEIVED",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "NOT RECEIVED"
  },
  {
    "id": 2,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/454/02/2026",
    "buyer": "PINACLE",
    "destination": "DUBAI",
    "quantity": 19.2,
    "unit": "MT",
    "containers": 1,
    "pricePerKg": 3.78,
    "grossUsd": 158519.71,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "not started",
    "product": "WASHED LIMU G-2& KAFFA G-2",
    "vessel": "NOT RECEIVED",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "NOT RECEIVED"
  },
  {
    "id": 3,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/455/02/2026",
    "buyer": "PINACLE",
    "destination": "DUBAI",
    "quantity": 19.2,
    "unit": "MT",
    "containers": 1,
    "pricePerKg": 3.1,
    "grossUsd": 126984.96,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "not started",
    "product": "SIDAMO G-4 & LEKEMPTI GR-4",
    "vessel": "NOT RECEIVED",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "NOT RECEIVED"
  },
  {
    "id": 4,
    "week": "W2026-08",
    "shipmentNo": "EXPO/COF/473/03/2026",
    "buyer": "VOLCAFE",
    "destination": "KOREA",
    "quantity": 19.2,
    "unit": "MT",
    "containers": 1,
    "pricePerKg": 2.97,
    "grossUsd": 125715.1104,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL SIDAMO GR-4",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-08-03",
    "notes": "RECEIVED"
  },
  {
    "id": 5,
    "week": "W2026-07",
    "shipmentNo": "EXPO/COF/500/05/2026",
    "buyer": "ETG",
    "destination": "JAPAN",
    "quantity": 36,
    "unit": "MT",
    "containers": 2,
    "pricePerKg": 2.75,
    "grossUsd": 218255.4,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL LEKEMPTI GR-4",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-07-17",
    "notes": "RECEIVED"
  },
  {
    "id": 6,
    "week": "W2026-07",
    "shipmentNo": "EXPO/COF/501/05/2026",
    "buyer": "ETG",
    "destination": "JAPAN",
    "quantity": 36,
    "unit": "MT",
    "containers": 2,
    "pricePerKg": 2.75,
    "grossUsd": 218255.4,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL LEKEMPTI GR-4",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-07-17",
    "notes": "RECEIVED"
  },
  {
    "id": 7,
    "week": "W2026-08",
    "shipmentNo": "EXPO/COF/508/05/2026",
    "buyer": "SUCAFINA",
    "destination": "SWEDEN",
    "quantity": 21,
    "unit": "MT",
    "containers": 1,
    "pricePerKg": 3.8,
    "grossUsd": 175927.08,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "WASHED SIDAMO GR- 2",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-08-03",
    "notes": "RECEIVED"
  },
  {
    "id": 8,
    "week": "W2026-08",
    "shipmentNo": "EXPO/COF/510/05/2026",
    "buyer": "SUCAFINA",
    "destination": "KOREA",
    "quantity": 19.2,
    "unit": "MT",
    "containers": 1,
    "pricePerKg": 3.69,
    "grossUsd": 156191.5,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "WASHED YIRGACHEFE G-2",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-08-03",
    "notes": "RECEIVED"
  },
  {
    "id": 9,
    "week": "W2026-08",
    "shipmentNo": "EXPO/COF/512/05/2026",
    "buyer": "VOLCAFE",
    "destination": "CHINA",
    "quantity": 19.2,
    "unit": "MT",
    "containers": 1,
    "pricePerKg": 3.78,
    "grossUsd": 160001.05,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "WASHED SIDAMO GR- 2",
    "vessel": "CMA",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-08-19",
    "notes": "RECEIVED"
  },
  {
    "id": 10,
    "week": "W2026-08",
    "shipmentNo": "EXPO/COF/515/06/2026",
    "buyer": "IMCO",
    "destination": "RUSSIA",
    "quantity": 19.2,
    "unit": "MT",
    "containers": 1,
    "pricePerKg": 3.56,
    "grossUsd": 150689,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "WASHED LIMU GR-2",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-08-03",
    "notes": "RECEIVED"
  },
  {
    "id": 11,
    "week": "W2026-08",
    "shipmentNo": "EXPO/COF/522/06/2026",
    "buyer": "SUCAFINA",
    "destination": "AUSTRALIA",
    "quantity": 20,
    "unit": "MT",
    "containers": 1,
    "pricePerKg": 2.6,
    "grossUsd": 114639.2,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL LEKEMPTI GR-4",
    "vessel": "CMA",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-08-19",
    "notes": "RECEIVED"
  },
  {
    "id": 12,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/523/06/2026",
    "buyer": "SUCAFINA",
    "destination": "AUSTRALIA",
    "quantity": 20,
    "unit": "MT",
    "containers": 1,
    "pricePerKg": 2.6,
    "grossUsd": 114639.2,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL LEKEMPTI GR-4",
    "vessel": "MAERSK",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "RECEIVED"
  },
  {
    "id": 13,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/524/06/2026",
    "buyer": "SUCAFINA",
    "destination": "AUSTRALIA",
    "quantity": 20,
    "unit": "MT",
    "containers": 1,
    "pricePerKg": 2.6,
    "grossUsd": 114639.2,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "not started",
    "product": "NATURAL LEKEMPTI GR-4",
    "vessel": "MAERSK",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "RECEIVED"
  },
  {
    "id": 14,
    "week": "W2026-08",
    "shipmentNo": "EXPO/COF/530/06/2026",
    "buyer": "TOUTON",
    "destination": "GERMANY",
    "quantity": 76.8,
    "unit": "MT",
    "containers": 4,
    "pricePerKg": 2.45,
    "grossUsd": 414817.54,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL DJIMMAH GR-5",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-08-28",
    "notes": "RECEIVED"
  },
  {
    "id": 15,
    "week": "W2026-08",
    "shipmentNo": "EXPO/COF/531/06/2026",
    "buyer": "TOUTON",
    "destination": "GERMANY",
    "quantity": 96,
    "unit": "MT",
    "containers": 5,
    "pricePerKg": 2.45,
    "grossUsd": 518498.4,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL DJIMMAH GR-5",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-08-25",
    "notes": "RECEIVED"
  },
  {
    "id": 16,
    "week": "W2026-08",
    "shipmentNo": "EXPO/COF/533/06/2026",
    "buyer": "STONEX",
    "destination": "GERMANY",
    "quantity": 96,
    "unit": "MT",
    "containers": 5,
    "pricePerKg": 2.44,
    "grossUsd": 516405.5,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL LEKEMPTI GR-5",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-08-17",
    "notes": "RECEIVED"
  },
  {
    "id": 17,
    "week": "W2026-08",
    "shipmentNo": "EXPO/COF/537/07/2026",
    "buyer": "VOLCAFE",
    "destination": "GERMANY",
    "quantity": 19.2,
    "unit": "MT",
    "containers": 1,
    "pricePerKg": 3.56,
    "grossUsd": 150688.82,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "WASHED LIMU GR-2",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-08-17",
    "notes": "RECEIVED"
  },
  {
    "id": 18,
    "week": "W2026-08",
    "shipmentNo": "EXPO/COF/538/07/2026",
    "buyer": "VOLCAFE",
    "destination": "JAPAN",
    "quantity": 24,
    "unit": "MT",
    "containers": 1,
    "pricePerKg": 2.62,
    "grossUsd": 138625.25,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL LEKEMPTI GR-4",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-08-25",
    "notes": "RECEIVED"
  },
  {
    "id": 19,
    "week": "W2026-08",
    "shipmentNo": "EXPO/COF/539/07/2026",
    "buyer": "TOUTON",
    "destination": "FRANCE",
    "quantity": 19.2,
    "unit": "MT",
    "containers": 1,
    "pricePerKg": 3.58,
    "grossUsd": 151535.39,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "WASHED LIMU GR-2",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-08-17",
    "notes": "RECEIVED"
  },
  {
    "id": 20,
    "week": "W2026-08",
    "shipmentNo": "EXPO/COF/540/07/2026",
    "buyer": "VOLCAFE",
    "destination": "JAPAN",
    "quantity": 24,
    "unit": "MT",
    "containers": 1,
    "pricePerKg": 2.62,
    "grossUsd": 138625.25,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL LEKEMPTI GR-4",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-08-25",
    "notes": "RECEIVED"
  },
  {
    "id": 21,
    "week": "W2026-08",
    "shipmentNo": "EXPO/COF/541/07/2026",
    "buyer": "SUCAFINA",
    "destination": "GERMANY",
    "quantity": 326.4,
    "unit": "MT",
    "containers": 17,
    "pricePerKg": 2.6,
    "grossUsd": 1870911.74,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL LEKEMPTI GR-4",
    "vessel": "MAERSK",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-08-26",
    "notes": "RECEIVED"
  },
  {
    "id": 22,
    "week": "W2026-09",
    "shipmentNo": "EXPO/COF/542/07/2026",
    "buyer": "SUCAFINA",
    "destination": "GERMANY",
    "quantity": 151.2,
    "unit": "MT",
    "containers": 8,
    "pricePerKg": 2.6,
    "grossUsd": 866672.35,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL LEKEMPTI GR-4",
    "vessel": "MAERSK",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-09-07",
    "notes": "RECEIVED"
  },
  {
    "id": 23,
    "week": "W2026-08",
    "shipmentNo": "EXPO/COF/543/07/2026",
    "buyer": "SUCAFINA",
    "destination": "GERMANY",
    "quantity": 172.8,
    "unit": "MT",
    "containers": 8,
    "pricePerKg": 2.46,
    "grossUsd": 937149,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL LEKEMPTI GR-5",
    "vessel": "MAERSK",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-08-26",
    "notes": "RECEIVED"
  },
  {
    "id": 24,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/544/07/2026",
    "buyer": "SUCAFINA",
    "destination": "GERMANY",
    "quantity": 216,
    "unit": "MT",
    "containers": 10,
    "pricePerKg": 2.46,
    "grossUsd": 1171436.26,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL LEKEMPTI GR-5",
    "vessel": "MAERSK",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "RECEIVED"
  },
  {
    "id": 25,
    "week": "W2026-08",
    "shipmentNo": "EXPO/COF/545/07/2026",
    "buyer": "VOLCAFE",
    "destination": "JAPAN",
    "quantity": 24,
    "unit": "MT",
    "containers": 1,
    "pricePerKg": 2.62,
    "grossUsd": 138625.25,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL LEKEMPTI GR-4",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-08-25",
    "notes": "RECEIVED"
  },
  {
    "id": 26,
    "week": "W2026-09",
    "shipmentNo": "EXPO/COF/546/07/2026",
    "buyer": "SUCAFINA",
    "destination": "GERMANY",
    "quantity": 216,
    "unit": "MT",
    "containers": 10,
    "pricePerKg": 2.55,
    "grossUsd": 1214293.68,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL LEKEMPTI GR-5",
    "vessel": "MAERSK",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-09-07",
    "notes": "RECEIVED"
  },
  {
    "id": 27,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/547/07/2026",
    "buyer": "LDC",
    "destination": "GERMANY",
    "quantity": 192,
    "unit": "MT",
    "containers": 10,
    "pricePerKg": 2.46,
    "grossUsd": 1041276.67,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "not started",
    "product": "NATURAL LEKEMPTI GR-5",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "RECEIVED"
  },
  {
    "id": 28,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/548/07/2026",
    "buyer": "WALTER MATTER",
    "destination": "GERMANY",
    "quantity": 115.2,
    "unit": "MT",
    "containers": 6,
    "pricePerKg": 2.55,
    "grossUsd": 647623.3,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "partial",
    "product": "NATURAL LEKEMPTI GR-5",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "RECEIVED"
  },
  {
    "id": 29,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/549/07/2026",
    "buyer": "LDC",
    "destination": "GERMANY",
    "quantity": 172.8,
    "unit": "MT",
    "containers": 8,
    "pricePerKg": 2.55,
    "grossUsd": 971434.94,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL LEKEMPTI GR-5",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "RECEIVED"
  },
  {
    "id": 30,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/550/07/2026",
    "buyer": "TOUTON",
    "destination": "GERMANY",
    "quantity": 210,
    "unit": "MT",
    "containers": 10,
    "pricePerKg": 2.53,
    "grossUsd": 1171303.98,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL LEKEMPTI GR-5",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "RECEIVED"
  },
  {
    "id": 31,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/551/07/2026",
    "buyer": "TOUTON",
    "destination": "GERMANY",
    "quantity": 210,
    "unit": "MT",
    "containers": 10,
    "pricePerKg": 2.54,
    "grossUsd": 1175933.64,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL LEKEMPTI GR-5",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "RECEIVED"
  },
  {
    "id": 32,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/554/07/2026",
    "buyer": "ETG",
    "destination": "KOREA",
    "quantity": 38.4,
    "unit": "MT",
    "containers": 2,
    "pricePerKg": 3.05,
    "grossUsd": 258203,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL LEKEMPTI GR-4",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "Pending",
    "notes": "RECEIVED"
  },
  {
    "id": 33,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/555/07/2026",
    "buyer": "ETG",
    "destination": "BELGIUM",
    "quantity": 76.8,
    "unit": "MT",
    "containers": 4,
    "pricePerKg": 2.75,
    "grossUsd": 465611.52,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL LEKEMPTI GR-5",
    "vessel": "CMA",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "RECEIVED"
  },
  {
    "id": 34,
    "week": "W2026-08",
    "shipmentNo": "EXPO/COF/556/07/2026",
    "buyer": "VOLCAFE",
    "destination": "GERMANY",
    "quantity": 122.4,
    "unit": "MT",
    "containers": 6,
    "pricePerKg": 2.74,
    "grossUsd": 739369.93,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL DJIMMAH GR-5",
    "vessel": "MAERSK",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-08-26",
    "notes": "RECEIVED"
  },
  {
    "id": 35,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/557/07/2026",
    "buyer": "LDC",
    "destination": "GERMANY",
    "quantity": 38.4,
    "unit": "MT",
    "containers": 2,
    "pricePerKg": 2.55,
    "grossUsd": 215874.43,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL LEKEMPTI GR-5",
    "vessel": "MAERSK",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "RECEIVED"
  },
  {
    "id": 36,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/558/07/2026",
    "buyer": "SUCAFINA",
    "destination": "GERMANY",
    "quantity": 324,
    "unit": "MT",
    "containers": 15,
    "pricePerKg": 2.67,
    "grossUsd": 1907155.37,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "partial",
    "product": "NATURAL LEKEMPTI GR-4",
    "vessel": "MAERSK",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "RECEIVED"
  },
  {
    "id": 37,
    "week": "W2026-09",
    "shipmentNo": "EXPO/COF/559/07/2026",
    "buyer": "SUCAFINA",
    "destination": "GERMANY",
    "quantity": 216,
    "unit": "MT",
    "containers": 10,
    "pricePerKg": 2.55,
    "grossUsd": 1214293.68,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL LEKEMPTI GR-5",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-09-11",
    "notes": "RECEIVED"
  },
  {
    "id": 38,
    "week": "W2026-09",
    "shipmentNo": "EXPO/COF/560/07/2026",
    "buyer": "SUCAFINA",
    "destination": "GERMANY",
    "quantity": 12,
    "unit": "MT",
    "containers": 1,
    "pricePerKg": 3.08,
    "grossUsd": 81482.02,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL SIDAMO GR-4",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-09-01",
    "notes": "RECEIVED"
  },
  {
    "id": 39,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/561/07/2026",
    "buyer": "JASMINE",
    "destination": "USA",
    "quantity": 7.2,
    "unit": "MT",
    "containers": 0,
    "pricePerKg": 3.87,
    "grossUsd": 61428.97,
    "paidUsd": 6142.897,
    "paymentStatus": "Partial",
    "cleaning": "completed",
    "product": "WASHED GUJI GR-2",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "RECEIVED"
  },
  {
    "id": 40,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/562/07/2026",
    "buyer": "JASMINE",
    "destination": "USA",
    "quantity": 6,
    "unit": "MT",
    "containers": 0,
    "pricePerKg": 3.87,
    "grossUsd": 51190.81,
    "paidUsd": 5119.081,
    "paymentStatus": "Partial",
    "cleaning": "completed",
    "product": "WASHED SIDAMO GR- 2",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "RECEIVED"
  },
  {
    "id": 41,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/563/07/2026",
    "buyer": "JASMINE",
    "destination": "USA",
    "quantity": 6,
    "unit": "MT",
    "containers": 0,
    "pricePerKg": 4.35,
    "grossUsd": 57540.06,
    "paidUsd": 5754.006,
    "paymentStatus": "Partial",
    "cleaning": "completed",
    "product": "WASHED YIRGACHEFFE GR-1",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "RECEIVED"
  },
  {
    "id": 42,
    "week": "W2026-09",
    "shipmentNo": "EXPO/COF/564/07/2026",
    "buyer": "LDC",
    "destination": "GERMANY",
    "quantity": 192,
    "unit": "MT",
    "containers": 10,
    "pricePerKg": 2.75,
    "grossUsd": 1164028.8,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL LEKEMPTI GR-5",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-09-04",
    "notes": "RECEIVED"
  },
  {
    "id": 43,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/565/07/2026",
    "buyer": "LDC",
    "destination": "GERMANY",
    "quantity": 96,
    "unit": "MT",
    "containers": 5,
    "pricePerKg": 2.75,
    "grossUsd": 582014.4,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "not started",
    "product": "NATURAL LEKEMPTI GR-5",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "RECEIVED"
  },
  {
    "id": 44,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/566/07/2026",
    "buyer": "COFI COM",
    "destination": "AUSTRALIA",
    "quantity": 19.2,
    "unit": "MT",
    "containers": 1,
    "pricePerKg": 2.75,
    "grossUsd": 116402.88,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL DJIMMAH GR-5",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "RECEIVED"
  },
  {
    "id": 45,
    "week": "W2026-08",
    "shipmentNo": "EXPO/COF/568/07/2026",
    "buyer": "PINACLE",
    "destination": "DUBAI",
    "quantity": 3,
    "unit": "MT",
    "containers": 0,
    "pricePerKg": 5.03,
    "grossUsd": 33267.41,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "WASHED GUJI GR-2",
    "vessel": "EMIRATES",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-08-03",
    "notes": "RECEIVED"
  },
  {
    "id": 46,
    "week": "W2026-08",
    "shipmentNo": "EXPO/COF/569/07/2026",
    "buyer": "PINACLE",
    "destination": "DUBAI",
    "quantity": 3,
    "unit": "MT",
    "containers": 0,
    "pricePerKg": 4.58,
    "grossUsd": 30357.33,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL KAFFA GR-2",
    "vessel": "EMIRATES",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-08-03",
    "notes": "RECEIVED"
  },
  {
    "id": 47,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/573/08/2026",
    "buyer": "SUCAFINA",
    "destination": "EGYPT",
    "quantity": 7.2,
    "unit": "MT",
    "containers": 0,
    "pricePerKg": 4.05,
    "grossUsd": 64286.14,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "WASHED SIDAMO GR- 2",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "RECEIVED"
  },
  {
    "id": 48,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/575/08/2026",
    "buyer": "SUCAFINA",
    "destination": "GERMANY",
    "quantity": 38.4,
    "unit": "MT",
    "containers": 2,
    "pricePerKg": 3.2,
    "grossUsd": 270901.25,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "WASHED SIDAMO GR- UG",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "RECEIVED"
  },
  {
    "id": 49,
    "week": "W2026-09",
    "shipmentNo": "EXPO/COF/576/08/2026",
    "buyer": "PINACLE",
    "destination": "DUBAI",
    "quantity": 3,
    "unit": "MT",
    "containers": 0,
    "pricePerKg": 5.03,
    "grossUsd": 33267.41,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "WASHED GUJI GR-2",
    "vessel": "EMIRATES",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-09-03",
    "notes": "RECEIVED"
  },
  {
    "id": 50,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/577/08/2026",
    "buyer": "CHINA CTEXIC",
    "destination": "CHINA",
    "quantity": 38.4,
    "unit": "MT",
    "containers": 2,
    "pricePerKg": 3.8,
    "grossUsd": 321695.23,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "WASHED LIMU GR-2",
    "vessel": "CMA",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "NOT RECEIVED"
  },
  {
    "id": 51,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/578/08/2026",
    "buyer": "CHINA CTEXIC",
    "destination": "CHINA",
    "quantity": 38.4,
    "unit": "MT",
    "containers": 2,
    "pricePerKg": 3.2,
    "grossUsd": 270901.25,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "WASHED SIDAMO GR- UG",
    "vessel": "CMA",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "NOT RECEIVED"
  },
  {
    "id": 52,
    "week": "W2026-09",
    "shipmentNo": "EXPO/COF/579/08/2026",
    "buyer": "PINACLE",
    "destination": "DUBAI",
    "quantity": 3,
    "unit": "MT",
    "containers": 0,
    "pricePerKg": 4.58,
    "grossUsd": 30357.33,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL KAFFA GR-2",
    "vessel": "EMIRATES",
    "contract": "YES",
    "status": "Delivered",
    "date": "2026-09-03",
    "notes": "RECEIVED"
  },
  {
    "id": 53,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/580/08/2026",
    "buyer": "LDC",
    "destination": "KOREA",
    "quantity": 57.6,
    "unit": "MT",
    "containers": 3,
    "pricePerKg": 2.88,
    "grossUsd": 365716.68,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "not started",
    "product": "NATURAL LEKEMPTI GR-5",
    "vessel": "NOT RECEIVED",
    "contract": "YES",
    "status": "Delivered",
    "date": "pending",
    "notes": "NOT RECEIVED"
  },
  {
    "id": 54,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/582/09/2026",
    "buyer": "PINACLE",
    "destination": "DUBAI",
    "quantity": 1.2,
    "unit": "MT",
    "containers": 0,
    "pricePerKg": 4.58,
    "grossUsd": 12142.93,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "NATURAL KAFFA GR-2",
    "vessel": "EMIRATES",
    "contract": "YES",
    "status": "Delivered",
    "date": "Pending",
    "notes": "RECEIVED"
  },
  {
    "id": 55,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/583/09/2026",
    "buyer": "PINACLE",
    "destination": "DUBAI",
    "quantity": 6,
    "unit": "MT",
    "containers": 0,
    "pricePerKg": 5.03,
    "grossUsd": 66534.83,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "completed",
    "product": "WASHED SIDAMO GR- 2",
    "vessel": "EMIRATES",
    "contract": "YES",
    "status": "Delivered",
    "date": "Pending",
    "notes": "RECEIVED"
  },
  {
    "id": 56,
    "week": "Pending",
    "shipmentNo": "EXPO/COF/584/09/2026",
    "buyer": "PINACLE",
    "destination": "DUBAI",
    "quantity": 6,
    "unit": "MT",
    "containers": 0,
    "pricePerKg": 5.33,
    "grossUsd": 70437.76,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "PENDING",
    "product": "NATURAL LEKEMPTI GR-4",
    "vessel": "EMIRATES",
    "contract": "YES",
    "status": "Delivered",
    "date": "Pending",
    "notes": "RECEIVED"
  }
];

export const sesameSeed: ExportRow[] = [
  {
    "id": 1,
    "week": "W2026-08",
    "shipmentNo": "SESAME/509/05/2026",
    "buyer": "ITOCHU",
    "destination": "JAPAN",
    "quantity": 114,
    "unit": "MT",
    "containers": 6,
    "pricePerKg": 1435,
    "grossUsd": 163590,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "COMPLETED",
    "product": "sesame humera",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Pending",
    "date": "2026-08-25",
    "notes": "GIVEN"
  },
  {
    "id": 2,
    "week": "Pending",
    "shipmentNo": "SESAME/519/06/2026",
    "buyer": "INVICTUS",
    "destination": "SLOVENIA",
    "quantity": 114,
    "unit": "MT",
    "containers": 6,
    "pricePerKg": 1380,
    "grossUsd": 157320,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "COMPLETED",
    "product": "sesame humera",
    "vessel": "MAERSK",
    "contract": "YES",
    "status": "Pending",
    "date": "Pending",
    "notes": "GIVEN"
  },
  {
    "id": 3,
    "week": "Pending",
    "shipmentNo": "SESAME/520/06/2026",
    "buyer": "INVICTUS",
    "destination": "JORDAN",
    "quantity": 190,
    "unit": "MT",
    "containers": 10,
    "pricePerKg": 1350,
    "grossUsd": 256500,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "COMPLETED",
    "product": "sesame humera",
    "vessel": "CMA CGM",
    "contract": "YES",
    "status": "Pending",
    "date": "Pending",
    "notes": "GIVEN"
  },
  {
    "id": 4,
    "week": "W2026-08",
    "shipmentNo": "SESAME/534/06/2026",
    "buyer": "ANHUI SINOFARMS CO.,LTD",
    "destination": "CHINA",
    "quantity": 190,
    "unit": "MT",
    "containers": 10,
    "pricePerKg": 1330,
    "grossUsd": 252700,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "COMPLETED",
    "product": "sesame humera",
    "vessel": "CMA CGM",
    "contract": "YES",
    "status": "Pending",
    "date": "2026-08-18",
    "notes": "GIVEN"
  },
  {
    "id": 5,
    "week": "W2026-07",
    "shipmentNo": "SESAME/535/06/2026",
    "buyer": "ANHUI WILMAR CORP",
    "destination": "CHINA",
    "quantity": 190,
    "unit": "MT",
    "containers": 10,
    "pricePerKg": 1330,
    "grossUsd": 252700,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "COMPLETED",
    "product": "sesame humera",
    "vessel": "CMA CGM",
    "contract": "YES",
    "status": "Pending",
    "date": "2026-07-30",
    "notes": "GIVEN"
  },
  {
    "id": 6,
    "week": "W2026-08",
    "shipmentNo": "SESAME/536/06/2026",
    "buyer": "AFG TRADING",
    "destination": "TURKEY",
    "quantity": 190,
    "unit": "MT",
    "containers": 10,
    "pricePerKg": 1330,
    "grossUsd": 252700,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "COMPLETED",
    "product": "sesame humera",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Pending",
    "date": "2026-08-03",
    "notes": "GIVEN"
  },
  {
    "id": 7,
    "week": "Pending",
    "shipmentNo": "SESAME/554/07/2026",
    "buyer": "AHCOF",
    "destination": "CHINA",
    "quantity": 228,
    "unit": "MT",
    "containers": 12,
    "pricePerKg": 1330,
    "grossUsd": 303240,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "COMPLETED",
    "product": "sesame humera",
    "vessel": "PIL",
    "contract": "YES",
    "status": "Pending",
    "date": "Pending",
    "notes": "GIVEN"
  },
  {
    "id": 8,
    "week": "W2026-07",
    "shipmentNo": "SESAME/567/07/2026",
    "buyer": "AFG TRADING",
    "destination": "TURKEY",
    "quantity": 190,
    "unit": "MT",
    "containers": 10,
    "pricePerKg": 1350,
    "grossUsd": 256500,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "COMPLETED",
    "product": "sesame humera",
    "vessel": "MSC",
    "contract": "YES",
    "status": "Pending",
    "date": "2026-07-30",
    "notes": "GIVEN"
  },
  {
    "id": 9,
    "week": "Pending",
    "shipmentNo": "SESAME/570/07/2026",
    "buyer": "ITOCHU",
    "destination": "JAPAN",
    "quantity": 114,
    "unit": "MT",
    "containers": 6,
    "pricePerKg": 1450,
    "grossUsd": 165300,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "PENDING",
    "product": "sesame humera",
    "vessel": "NOT GIVEN",
    "contract": "YES",
    "status": "Pending",
    "date": "Pending",
    "notes": "NOT GIVEN"
  },
  {
    "id": 10,
    "week": "Pending",
    "shipmentNo": "SESAME/571/07/2026",
    "buyer": "ITOCHU",
    "destination": "JAPAN",
    "quantity": 190,
    "unit": "MT",
    "containers": 10,
    "pricePerKg": 1450,
    "grossUsd": 275500,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "PENDING",
    "product": "sesame humera",
    "vessel": "NOT GIVEN",
    "contract": "YES",
    "status": "Pending",
    "date": "Pending",
    "notes": "NOT GIVEN"
  },
  {
    "id": 11,
    "week": "Pending",
    "shipmentNo": "SESAME/572/07/2026",
    "buyer": "XIAMEN",
    "destination": "CHINA",
    "quantity": 190,
    "unit": "MT",
    "containers": 10,
    "pricePerKg": 1240,
    "grossUsd": 235600,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "COMPLETED",
    "product": "sesame Wollega",
    "vessel": "CMA CGM",
    "contract": "YES",
    "status": "Pending",
    "date": "Pending",
    "notes": "GIVEN"
  },
  {
    "id": 12,
    "week": "Pending",
    "shipmentNo": "SESAME/574/08/2026",
    "buyer": "INVICTUS",
    "destination": "SLOVENIA",
    "quantity": 114,
    "unit": "MT",
    "containers": 6,
    "pricePerKg": 1330,
    "grossUsd": 151620,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "PENDING",
    "product": "sesame humera",
    "vessel": "NOT GIVEN",
    "contract": "NO",
    "status": "Pending",
    "date": "Pending",
    "notes": "NOT GIVEN"
  },
  {
    "id": 13,
    "week": "Pending",
    "shipmentNo": "SESAME/581/08/2026",
    "buyer": "ITOCHU",
    "destination": "JAPAN",
    "quantity": 114,
    "unit": "MT",
    "containers": 6,
    "pricePerKg": 1500,
    "grossUsd": 171000,
    "paidUsd": 0,
    "paymentStatus": "Open",
    "cleaning": "PENDING",
    "product": "sesame humera",
    "vessel": "NOT GIVEN",
    "contract": "YES",
    "status": "Pending",
    "date": "Pending",
    "notes": "NOT GIVEN"
  }
];
